export const dsaQuestions = [
    {
        question: 'Which data structure uses LIFO principle?',
        optionA: 'Queue',
        optionB: 'Stack',
        optionC: 'Array',
        optionD: 'Linked List',
        correctAnswer: 'Stack',
        difficulty: 'easy',
    },
    {
        question: 'Time complexity of binary search?',
        optionA: 'O(n)',
        optionB: 'O(log n)',
        optionC: 'O(n log n)',
        optionD: 'O(1)',
        correctAnswer: 'O(log n)',
        difficulty: 'easy',
    },
    {
        question: 'Which traversal is used in BFS?',
        optionA: 'Stack',
        optionB: 'Queue',
        optionC: 'Recursion',
        optionD: 'Heap',
        correctAnswer: 'Queue',
        difficulty: 'medium',
    },
    {
        question: 'Which data structure is used for recursion?',
        optionA: 'Queue',
        optionB: 'Array',
        optionC: 'Stack',
        optionD: 'Tree',
        correctAnswer: 'Stack',
        difficulty: 'easy',
    },
    {
        question: 'Worst case time complexity of quicksort?',
        optionA: 'O(n)',
        optionB: 'O(n log n)',
        optionC: 'O(log n)',
        optionD: 'O(n²)',
        correctAnswer: 'O(n²)',
        difficulty: 'hard',
    },
    {
        question: 'Which data structure uses FIFO principle?',
        optionA: 'Stack',
        optionB: 'Queue',
        optionC: 'Tree',
        optionD: 'Graph',
        correctAnswer: 'Queue',
        difficulty: 'easy',
    },
    {
        question: 'Which data structure uses LIFO principle?',
        optionA: 'Queue',
        optionB: 'Array',
        optionC: 'Stack',
        optionD: 'Linked List',
        correctAnswer: 'Stack',
        difficulty: 'easy',
    },
    {
        question: 'What is the time complexity of binary search?',
        optionA: 'O(n)',
        optionB: 'O(log n)',
        optionC: 'O(n log n)',
        optionD: 'O(1)',
        correctAnswer: 'O(log n)',
        difficulty: 'easy',
    },
    {
        question: 'Which data structure is used for BFS traversal?',
        optionA: 'Stack',
        optionB: 'Queue',
        optionC: 'Array',
        optionD: 'Tree',
        correctAnswer: 'Queue',
        difficulty: 'easy',
    },
    {
        question: 'Which data structure is used for DFS traversal?',
        optionA: 'Queue',
        optionB: 'Stack',
        optionC: 'Heap',
        optionD: 'Graph',
        correctAnswer: 'Stack',
        difficulty: 'easy',
    },
    {
        question: 'Which is not a linear data structure?',
        optionA: 'Array',
        optionB: 'Stack',
        optionC: 'Queue',
        optionD: 'Tree',
        correctAnswer: 'Tree',
        difficulty: 'easy',
    },
    {
        question: 'Which sorting algorithm is fastest on average?',
        optionA: 'Bubble Sort',
        optionB: 'Selection Sort',
        optionC: 'Quick Sort',
        optionD: 'Insertion Sort',
        correctAnswer: 'Quick Sort',
        difficulty: 'medium',
    },
    {
        question: 'What is the worst case time complexity of quick sort?',
        optionA: 'O(n)',
        optionB: 'O(n log n)',
        optionC: 'O(log n)',
        optionD: 'O(n²)',
        correctAnswer: 'O(n²)',
        difficulty: 'medium',
    },
    {
        question: 'Which sorting algorithm is stable?',
        optionA: 'Quick Sort',
        optionB: 'Heap Sort',
        optionC: 'Merge Sort',
        optionD: 'Selection Sort',
        correctAnswer: 'Merge Sort',
        difficulty: 'medium',
    },
    {
        question: 'What is the best case time complexity of insertion sort?',
        optionA: 'O(n²)',
        optionB: 'O(n log n)',
        optionC: 'O(n)',
        optionD: 'O(log n)',
        correctAnswer: 'O(n)',
        difficulty: 'medium',
    },
    {
        question: 'Which data structure is best for implementing recursion?',
        optionA: 'Queue',
        optionB: 'Stack',
        optionC: 'Array',
        optionD: 'Linked List',
        correctAnswer: 'Stack',
        difficulty: 'easy',
    },
    {
        question: 'Which traversal gives sorted output in BST?',
        optionA: 'Preorder',
        optionB: 'Postorder',
        optionC: 'Inorder',
        optionD: 'Level order',
        correctAnswer: 'Inorder',
        difficulty: 'medium',
    },
    {
        question: 'Which data structure is used in heap sort?',
        optionA: 'Queue',
        optionB: 'Stack',
        optionC: 'Heap',
        optionD: 'Tree',
        correctAnswer: 'Heap',
        difficulty: 'easy',
    },
    {
        question: 'What is the maximum number of children in a binary tree node?',
        optionA: '1',
        optionB: '2',
        optionC: '3',
        optionD: 'Unlimited',
        correctAnswer: '2',
        difficulty: 'easy',
    },
    {
        question: 'Which data structure is used to detect cycles in a graph?',
        optionA: 'Queue',
        optionB: 'Stack',
        optionC: 'Union-Find',
        optionD: 'Array',
        correctAnswer: 'Union-Find',
        difficulty: 'medium',
    },
    {
        question: 'What is the time complexity of accessing an element in an array?',
        optionA: 'O(n)',
        optionB: 'O(log n)',
        optionC: 'O(1)',
        optionD: 'O(n log n)',
        correctAnswer: 'O(1)',
        difficulty: 'easy',
    },
    {
        question: 'Which data structure allows insertion and deletion at both ends?',
        optionA: 'Queue',
        optionB: 'Deque',
        optionC: 'Stack',
        optionD: 'Array',
        correctAnswer: 'Deque',
        difficulty: 'medium',
    },
    {
        question: 'Which algorithm is used to find shortest path?',
        optionA: 'DFS',
        optionB: 'BFS',
        optionC: 'Dijkstra',
        optionD: 'Binary Search',
        correctAnswer: 'Dijkstra',
        difficulty: 'medium',
    },
    {
        question: 'Which tree is used in database indexing?',
        optionA: 'Binary Tree',
        optionB: 'AVL Tree',
        optionC: 'B-Tree',
        optionD: 'Heap',
        correctAnswer: 'B-Tree',
        difficulty: 'medium',
    },
    {
        question: 'Which data structure uses key-value pairs?',
        optionA: 'Array',
        optionB: 'Stack',
        optionC: 'Hash Table',
        optionD: 'Queue',
        correctAnswer: 'Hash Table',
        difficulty: 'easy',
    },
    {
        question: 'What is the height of a single node tree?',
        optionA: '0',
        optionB: '1',
        optionC: '2',
        optionD: '-1',
        correctAnswer: '1',
        difficulty: 'easy',
    },
    {
        question: 'Which traversal is also known as BFS?',
        optionA: 'Inorder',
        optionB: 'Preorder',
        optionC: 'Postorder',
        optionD: 'Level Order',
        correctAnswer: 'Level Order',
        difficulty: 'easy',
    },
    {
        question: 'Which sorting algorithm uses divide and conquer?',
        optionA: 'Bubble Sort',
        optionB: 'Merge Sort',
        optionC: 'Insertion Sort',
        optionD: 'Selection Sort',
        correctAnswer: 'Merge Sort',
        difficulty: 'medium',
    },
    {
        question: 'Which algorithm is used for minimum spanning tree?',
        optionA: 'Dijkstra',
        optionB: 'Kruskal',
        optionC: 'DFS',
        optionD: 'BFS',
        correctAnswer: 'Kruskal',
        difficulty: 'medium',
    },
    {
        question: 'Which data structure is used in undo operation?',
        optionA: 'Queue',
        optionB: 'Stack',
        optionC: 'Tree',
        optionD: 'Graph',
        correctAnswer: 'Stack',
        difficulty: 'easy',
    },
    {
        question: 'Which algorithm uses greedy approach?',
        optionA: 'Merge Sort',
        optionB: 'Quick Sort',
        optionC: 'Dijkstra',
        optionD: 'Binary Search',
        correctAnswer: 'Dijkstra',
        difficulty: 'medium',
    },
    {
        question: 'What is the worst case complexity of linear search?',
        optionA: 'O(log n)',
        optionB: 'O(n)',
        optionC: 'O(1)',
        optionD: 'O(n log n)',
        correctAnswer: 'O(n)',
        difficulty: 'easy',
    },
    {
        question: 'Which data structure is non-linear?',
        optionA: 'Array',
        optionB: 'Linked List',
        optionC: 'Graph',
        optionD: 'Queue',
        correctAnswer: 'Graph',
        difficulty: 'easy',
    },
    {
        question: 'Which algorithm is used for topological sorting?',
        optionA: 'DFS',
        optionB: 'Binary Search',
        optionC: 'Merge Sort',
        optionD: 'Heap Sort',
        correctAnswer: 'DFS',
        difficulty: 'medium',
    },
    {
        question: 'Which structure is best for priority scheduling?',
        optionA: 'Queue',
        optionB: 'Stack',
        optionC: 'Heap',
        optionD: 'Array',
        correctAnswer: 'Heap',
        difficulty: 'easy',
    },
];
